#!/usr/bin/env bash


#export objectName="unimportant-hello:mirage335/debian-mirage335/debian:jessie"
export objectName="marlinbuilder-shell:local_debian_jessie-local/debian:jessie"

_deriveBaseImageContainerNames

#_launch() {
#	_run
#}





