#!/usr/bin/env bash


#export objectName="unimportant-hello:mirage335/debian-mirage335/debian:jessie"
export objectName="unimportant-gui:local_debian_jessie-local/debian:jessie"

_deriveBaseImageContainerNames

_setup() {
	_start
	
	"$scriptAbsoluteLocation" _test
	
	"$scriptAbsoluteLocation" _build "$@"
	
	echo -e -n '\E[1;33;41m *****BREAKPOINT, press any key... \E[0m'
	read
	#echo
	
	_stop
}

# "$1" == shared project directory
_run() {
	
	#docker run -it --name "$containerObjectName"_"$sessionid" --rm "$imageObjectName" "$@"
	#docker run -it -e LOCAL_USER_ID=`id -u $USER` myimage
	
	#http://wiki.ros.org/docker/Tutorials/GUI
	
	XSOCK=/tmp/.X11-unix
	XAUTH=/tmp/.docker.xauth."$sessionid"
	touch $XAUTH
	xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
	
	sharedProjectDir=$(_getAbsoluteLocation "$1")
	shift
	docker run -it --name "$containerObjectName"_"$sessionid" -e LOCAL_USER_ID=`id -u $USER` --rm -e DISPLAY=$DISPLAY -v $XSOCK:$XSOCK:rw -v $XAUTH:$XAUTH:rw -e "XAUTHORITY=${XAUTH}" -v "$HOME"/Downloads:/home/user/Downloads:rw -v "$sharedProjectDir":/home/user/project:rw "$imageObjectName" "$@"
	
	#docker run -it --name "$containerObjectName"_"$sessionid" -e LOCAL_USER_ID=`id -u $USER` --rm -e DISPLAY=$DISPLAY -v $XSOCK:$XSOCK:rw -v $XAUTH:$XAUTH:rw -e "XAUTHORITY=${XAUTH}" -v "$HOME"/Downloads:/home/user/Downloads:rw "$imageObjectName" "$@"
	
}


_launch() {
	
	docker start -ia "$containerObjectName" "$@"
	
}


_launch() {
	_run "$@"
}





