#!/usr/bin/env bash

#export objectName="marlinbuilder-marlinbuilder:local_debian_jessie-local/debian:jessie"
export objectName="derivative-derivative:gui_local_debian_jessie-gui:local_debian_jessie"

_deriveBaseImageContainerNames


#_launch() {
#	_run "$@"
#}





