#!/usr/bin/env bash

export objectName="marlinbuilder-marlinbuilder:local_debian_jessie-local/debian:jessie"

_deriveBaseImageContainerNames

_setup() {
	_start
	
	"$scriptAbsoluteLocation" _test
	
	"$scriptAbsoluteLocation" _build "$@"
	
	echo -e -n '\E[1;33;41m *****BREAKPOINT, press any key... \E[0m'
	read
	#echo
	
	_stop
}


_run() {
	
	#docker run -it --name "$containerObjectName"_"$sessionid" --rm "$imageObjectName" "$@"
	#docker run -it -e LOCAL_USER_ID=`id -u $USER` myimage
	
	#http://wiki.ros.org/docker/Tutorials/GUI
	
	XSOCK=/tmp/.X11-unix
	XAUTH=/tmp/.docker.xauth."$sessionid"
	touch $XAUTH
	xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
	
	sharedGuestProjectDir="/home/user/project"
	
	sharedHostProjectDir=$(_searchBaseDir "$@")
	
	if [[ "$sharedHostProjectDir" == "" ]]
	then
		sharedHostProjectDir="$safeTmp"/shared
		mkdir -p "$sharedHostProjectDir"
	fi
	
	
	#http://stackoverflow.com/questions/15420790/create-array-in-loop-from-number-of-arguments
	local processedArgs
	local currentArg
	local currentResult
	processedArgs=()
	for currentArg in "$@"
	do
		currentResult=$(_localDir "$currentArg" "$sharedHostProjectDir" "$sharedGuestProjectDir")
		processedArgs+=("$currentResult")
	done
	
	
	docker run -it --name "$containerObjectName"_"$sessionid" -e LOCAL_USER_ID=`id -u $USER` --rm -e DISPLAY=$DISPLAY -v $XSOCK:$XSOCK:rw -v $XAUTH:$XAUTH:rw -e "XAUTHORITY=${XAUTH}" -v "$HOME"/Downloads:/home/user/Downloads:rw -v "$sharedHostProjectDir":"$sharedGuestProjectDir":rw "$imageObjectName" /bin/bash "${processedArgs[@]}"
	
	
	
}


_launch() {
	
	docker start -ia "$containerObjectName" "$@"
	
}


_launch() {
	_run "$@"
}





